services:
- docker
script: docker-compose run test
notifications:
  slack:
    secure: ROZopkSeDR8fyK9WuScctFem6CGt/sMBdjxT0zDwOP0M71l6y5rBwuO2jnOhzNqo6pQMLZSrVHr8GS3Zm6Y9+CJXWeRKPNoNjq616MFJaE/jad+4hq6ESiSCPC2JDVGw57huixytGAGdr+w8h/ELBDsBJhgk+c/UwEv9wgWvHdl3JP7wAvR+hN3Xqqwr0z+mtzec91arryD7qK4HaZx77lA9jww8FMi5pZO1S8muJWofZaUcRf4xrv4hM3TSzfxuG9ctBKKNLoGjs30Qax5HgDsqxGHOYRJUOqgfYrqSqkvzgQQMNy5hVdfYIR+aTpnGIoAuEDEpUeaH6xsRHSD3f5im4VV0jCIsHZ+WLJjT94KO+ji10Cb3R3MOdlg/PfOCT0+c2UbRIQ/k1+nxCJWjFY/8yfyFfiMd7GiknGCmmipW4KUN4OHUmYMqGM6BADvTWg1u20x+PDPIlvGGJstuUTSE2A4P30b5p3TPUtRN5/8oF1x4KD9edeWVxdzvk9DqN1w2obop7ZO3WUiiQgvKbmSUek9biIne4p6kT8QsattAY3/dT2BZV4BkE9JC86sqpIMe4Niiga2eYQuwJcM/6B93CITsNGGdxUwCcjJ99WBe14S6MX1DS2UmPexFb+ozY4Dta1khK/9kZUOV4qYiobwE5YXtNt0hJHI23agSuVA=
