version: '3'
services:
  windbreaker-badges:
    build: .
    command: 'npm start'
    volumes:
      - .:/usr/windbreaker-badges
      - /usr/windbreaker-badges/node_modules
    environment:
      SERVICE_ENVIRONMENT: 'docker'
  test:
    build: .
    command: 'npm run test:docker:ci'
    volumes:
      - .:/usr/windbreaker-badges
      - /usr/windbreaker-badges/node_modules
    environment:
      SERVICE_ENVIRONMENT: 'docker'
