version: '3'
services:
  windbreaker-badges:
    build: .
    command: 'npm start'
    depends_on:
      - postgres
    volumes:
      - .:/usr/windbreaker-badges
      - /usr/windbreaker-badges/node_modules
    environment:
      SERVICE_ENVIRONMENT: 'docker'
  test:
    build: .
    command: 'npm run test:docker:ci'
    depends_on:
      - postgres
    volumes:
      - .:/usr/windbreaker-badges
      - /usr/windbreaker-badges/node_modules
    environment:
      SERVICE_ENVIRONMENT: 'docker'
  postgres:
    image: 'postgres:9.6.3-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'windbreaker'
    ports:
      - 5432
